left_hashtags_an = ["LiberalClueless","studentloanslivesmatter","BOYCOTTFRITOLAYS","solidarity","FreeBritney","FREEDMEN","ADOS", 
            "TRUTH", "freepalestine", "PalestinianLivesMatter", "FREEPALESTINIAN", "DefundthePolice", "BLM", "EatTheRich", 
            "CODEPINK", "climatechange", "Whee", "ModiHtaoDeshBchao", "modi_rojgar_do", "Truenews", 
            "freeTheOuighours", "SosColombia", "GazaUnderAttack", "savesheikhjarrah", "BlackLiveMatter", "palestine", 
            "govegan", "videoscopie", "vidÃ©oscopie", "OuÃ¯gours", "Biden", "lockthemup", 
            "CNN", "gunban", "ArrestTrumpNow", "GetTheDamnShots", "protectyourfamily", 
            "Feminism", "ISTANDWITHBIDEN", "climatechange", "Biden2024", "wearmasks", 
            "diyletscreate", "SAVEGREENNCARD", "trumpbelongsinprison", "WALKAWAYREPUBLICANS", "ArrestTrump", 
            "thoughtsandprayers", "DefundPublicEducation", "BelieveAllWomen", "NaturalSelection", "lockhimup", "MeToo", 
            "PayYourTaxesTrump", "TraitorTrump", "glory", "RentFree", "BULLIESARECOWARDS", "RepublicansAreHeartless", 
            "BOOSTERSHOT", "NoMoreWa", "Trumpisafraud", "stophazaragenocide", "DumpTrump", 
            "IAmSooooooooTiredOfGOVERNMENTCIRCUS", "Bidenflation", "CancelRepublicans", 
            "PeopleMakingMoneySellingBooksLOADWITHINFOYETtrumpNOTARRESTEDWTH", "trumpworstpresidentever", 
            "ArrestDonaldTrump", "HeyFauxNewsAmericansarepoor", "Educated", "TrumpisgoingtoJail", "taxtherich",
            "trumpcrimefamilyisgoingdown", "republicansarecomplicit", "StudentsLivesMatters", 
            "RepugnaKLANs", "istandwithObama", "GoFundMe", "amazing", "AI", "NoOneWinsWhenALifeIsLost", 
            "PutinbotsForTrump", "trumpbelongsinjail", "westillslavesbutpayingtaxes", "Revolution", 
            "ALLLIVESMATTER", "Obama", "Democracy", "gunreform"]
left_hashtags_ak = ["45", "1", "44", "stopthelieact", "LarryKingLegend", "RIPLarryKing", "GaryMcfall", "BrettHall", "DEMOCRATS", 
"TRUMPISATRAITOR", "resist", "timeforachange", "FAUCI2024", "Welovefauci", "TEAMFAUCI", "tMMTheMeekMovement", 
"StreetEpistemology", "VeryInspiringSpeech", "blackgirlmagic", "AmandaGorman", "Genuis", "ChadBlack", "CongratsKamalaDHarris",
" timeforachange", "standwithugandan"," Free", "BlackGirlsRock", "byefelicia", "45thecreepcrook", 
"DonaldTrumpMadeAmericaABananaRepuclic", "10....drum", "freekodak", "FREECHAPO"," freeJoeexotic"," Pardons4Cash"," FreeBiGMeech",
" BLACKS"," GodKeepBidenHarrisSafe", "JustMonika", "cnbc", "weaponized", "ShepardSmith"," DonaldWho"," lockhimup", 
"mitchYouWillBeHeldAccountableAsWell", "justicematters", "VeteransAgainstTrump", "standwithugandan", "VoteBlue2022", 
"OURFUTUREMATTERS", "trumpRICO", "BLACKLOVE", "LiberateFloriduh", "Trumpworstpresidentever", "senatorlankfraud", 
"LankfordDonotBackPeddleKnow", "JadeSacker", "TheGreatReset", "EugeneGoodmanIsAHero", "NoWordsJustTears", "convicttrump", 
"trumpisapathologicalliar", "trumpisatraitor", "LOCKTRUMPUP", "ITMFA", "GymJordanResign", "Donnythebunkerboy", "BYEBYECINNAMONHITLER", 
"staystrong", "PeopleAreForgettingtrumpHasATelephoneAndenablersStillDoinghisDeeds", "DeportMelania", "Impeach45Now", "IMPEACH45NOW",
" LeopardsAteMyFace", "bunkerboy", "freejulianassangenow", "impeachpelosi", "DumpTrump", "hangallpoliticians", "IMPEACH_TRUMP_2021", 
"AmericanHistory101", "trumptoprison", "impeachtrump", "RECALLCRUZ", "CLOSEFOXNEWS", "PUNISHTRAITORSOFTHEREPUBLIC", "HANGTHETRAITORS", 
"SQUASHTHEINSURRECTION", "45INORANGEJUMPSUIT", "agentprovocateurslivesmatter", "BriannaKeilar", "resigntedcruz", "weloveBK", 
"RecallCruz", "RECALLCRUZ", "capitalriot", "AwarenessConsciousness", "ItalyDidIt", "TooLateTed", "impeachtrump", 
"ChargeTrumpPardonRioters", "Italydidi", "ItalyGate", "Italygate", "LockHimUp", "Trumpresign", "socialism", "payattention", 
"thesupremestudy", "TrumpforGuantanamoBay2021", "fokDonaldTrump", "thegreatawakening", "joebiden", "CNN", "cnn", "ChrisCuomo", 
"BriannaKeller", "Deplorables", "RIPTrumpRemoveIndictPrison", "removeimpeachindict", "hangpelosi", "MAGAMORONS", "jailtrump", 
"RemoveTraitorTrumpFromOfficeNow", "CNNRAW", "GetOutOfCongressEvilPelosi", "BidenMakeAmericaProudAgain", "Biden", "GOPTraitors", 
"RIPGOP", "stopcryingbabies", "GrimWeeper", "impeachedtrump"]

left_w = ["Defund", "boycottcocacola", "ReformSection230", "FRAUDCI", "OverthrowModi", "GetVaccinated", "DiaperDon", 
         "PrayForPalestine", "stopisraeliterrorism", "EATtheRiCh", "refugeeswelcome", "wesupportpalestine", "freepalÃ¤stina",
         "nomoretrumps2024", "OBAMASTHIRDTERM", "FREE_PALESTINE", "savepalestine", "SavePalestine", "StandWithPalestine",
         "PrayForPalestine", "GazaUnderAttack", "SaveSheikhJarrah", "Gaza_Under_Attack", "israeldontexist", "stopthegenocide", 
          "palestinianlivesmatter", "JOEBIDENWON2020", "BLM", "SosColombia", "SOS", "ColombiaSOS"]

left_hashtags = left_hashtags_an + left_hashtags_ak + left_w

right_hashtags_an = ["cowards", "generalstrike", "DEBO", "TheFederalist", "TRUMPWON", "trump2024baby", "TuckkkerCarlson", 
                     "letsgobrandon", "FJB", "unacceptable", "DemonRats", "BJP", "BOYCOTT", "bantwitter", "dalal", 
                     "MatvinScott", "AlexandriaOcasioSmollett", 
                     "Impeachbiden", "BLOODYBIDEN", "HangAllTraitors", "impeach46", "wewanttrumpback",  
                     "TRUMP2024", "BloodbathBiden2024", "BLAMEBIDEN", "STRANDED", 
                     "FireBidenAdmin",  "SeeEndEnd", "biden_impeachment", "FckLyingJoeBiden", "FOXNEWS", 
                     "ImpeachBidenHarrisNOW", "NIX46", "stolenelection", "Endcnn", "vaxno", "typicalliberal", "TRUMP", 
                     "WeKnowTrumpWon2020", "thesepeopleareriskingtheirlivesforgijoe", "cancelCNN", "BombChina", 
                     "SloppyJoe", "leftistpropaganda", "ReinstateTrump", "Talibiden", "KabulBiden", "BidenYoureFired", 
                     "CNNisTaliban", "boycottcnn", "CNNsupportstaliban", "resignedbiden", "closedowncnnnow", 
                     "FakenewsCNN", "CNNisgarbage", "JoeBidenIsACrackhead", "arrestbillgates", "BIDENISPISSINGONBEAUSGRAVE",
                     "ItsACult", "UNVACCINATED", "herdimmunity", "cnnisfakenews", "deletefacebook", "bidensbloodbath", 
                     "moneyisFAKE", "clintons", "BIDENLIES", "COVIDVAXXKILLS", "Stillmypresident", "BidenCrimeFamily", 
                     "CNNISHOTGARBAGEINTHESUN", "panic", "cnnclowns", "creepyjoe", "exposecnn", 
                     "DemocratsIQisPotato", "TrumpWon", "Poisons", "staged", "cnnlied", 
                     "communistnewsnetwork", "ChinaNewsNetwork", "ChinaVirus", "CNNCertainlyNotNews" ]

right_hashtags_ak = [ "46", "2", "25", "AMERICAN", "mikelindell", "GaryTuchman", "BUCKFIDEN", "MoscowMitch", "TRUMPWON", "Qanon", 
"CNNCertainlyNotNews", "Maryland", "Impeach46", "impeachsnifferjoe", "ImpeachBidenNow", " TrumpWon", "impeachjoebiden", 
"IMPEACHBIDEN2021", "NCSWIC", "CNNLovesTrump", "fakenewscnn", " 46Illegitimate", " FaKeNeWs", "fakenews", "forcethevote",
" traitorjlo", "STOPTHESTEAL", "stopthesteal", "NOTMYVICEPRESIDENT", "NOTMYPRESIDENT",  "NoMyPresident", "notmypotaohead",
" tulsi2024"," JBNotMy46"," FJB"," ScrewBiden2021"," HailtotheThief"," IMPEACHCHINAJOE"," joebidenisnotmypresident", "NotMyPedo", 
"voterFRAUD", "NotMyPotato", "IBelieveTaraReade", "BIDENFORPRISON", "JoeDidntWin"," trump2024"," Trump"," MAGA"," impeachment2022",
" STEVEBANNON"," ripallwevelost"," NotmyPresident"," BidAncheated", " PATRIOTPARTY"," WAKEUPAMERICA"," stand"," fakePotUS",
" 46ophile"," TRUMP4EVER", "ByeDon"," ByebyeDon"," TRUMP2024"," hangfakenewsreporters"," weloveBK"," boycottcnn"," Scamdemic",
" MasksDontHelp", "fakenews", "GRAHAMSLASTTERM","InsideJob","Chairsforthetroops", "TrumpistNaziTraitors","republicansarecomplicit",
" ELECTIONFRAUD"," BIDENCRIMEFAMILY", "NotMyPillow", "HoldTrumpAccountable", "NoMercy", "CNNTapes", "JamesLankford", "Vote", 
"boycottmypillowguy", "NeverAgain", "daiperdon", "BidenNeverMyPresident", "quidprojoe", "StopBlamingTrump", "Doublestandard", 
"Pressure", "JesusSaves", "trump2021", "trumpforprison2021", "impeachbiden", "ThisisAmerica", "25thAmendment", 
"ExecuteCongress2021", "PELOSILOVESTRUMP", "boycotthallmarkcards", "Trumptoipas", "boycottamazon", "ResistBiden", "Trump2024", 
"CANCELDEMOCRATS", "cancelcnn", "IMPEACHE", "Trump2020", "AshleyBabbitt", "InvokeThe25th", "defundCNN", "defundthemedia", 
"25thAmendmentInvoke", "25thfor45th", "GoTrump", "REPARATIONS2021", "thewhitehouseisnottoprotectcrimebosses", "lyingTed"]

right_w = ["BoycottTheNewYorkTimes", "impeachthebidenadministration", "BorderCrisis", "Bidenlies", "trumpwasright",  
          "TRUCKERS", "istandwithisrael", "istandwithisrael", "indiastandwithisrael", "novaccinemandates", "LetsGoBrandon",
          "2020stolenelection", "TrudeauCrimeMinister", "dustbinTruedope", "ARRESTCRIMEMINISTERTRUDEAU", "FLUSHTHETURD",
          "DONTRUMPJR2024", "MakeCaliforniaRedAgain", "fkjoebiden", "StandForIsrael", "StayStrongIsrael", "indiawithisrael",
          "apartheidisrael", "TrumpWon", "impeach46", "FckJoeBiden", "notmypresident"]

right_hashtags = right_hashtags_an + right_hashtags_ak + right_w

#print(len(right_hashtags))
#print(len(left_hashtags))